"""Alembic env.py — generated by pylar's MigrationsRunner.

This file is checked in with the rest of your project. Edit it if you need
custom comparison hooks, per-environment behaviour, or extra include/exclude
filters. Pylar passes the target metadata and a synchronous database URL
through ``context.config.attributes``, so there is no need to bootstrap the
application from inside this file.
"""
from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

config = context.config

# Migrations should not hang forever when another process holds a
# table-level lock (e.g. a long-running ``pylar serve`` instance).
# 30 seconds is generous for legitimate DDL but tight enough to
# surface "another process is using this table" issues quickly.
# Set via PostgreSQL connection options so the timeout is active from
# the moment the connection opens — no separate SET statement that
# could start an implicit transaction before Alembic's own
# begin_transaction() and confuse the migration runner.
_PG_TIMEOUT_OPTIONS = "-c lock_timeout=30000 -c statement_timeout=60000"

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = config.attributes.get("target_metadata")


def run_migrations_offline() -> None:
    url = config.attributes["url"]
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    url = config.attributes["url"]
    engine_kwargs: dict[str, object] = {"poolclass": pool.NullPool}
    if url.startswith("postgresql"):
        engine_kwargs["connect_args"] = {"options": _PG_TIMEOUT_OPTIONS}

    connectable = create_engine(url, **engine_kwargs)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
