"""AES-256-GCM authenticated encryption.

The :class:`Encrypter` is pylar's answer to Laravel's
``Illuminate\\Encryption\\Encrypter``. It provides symmetric
encrypt/decrypt with authentication (GCM tag), so tampering is
detected on decryption.

The key is derived from ``APP_KEY`` in the environment, which must
be a ``base64:``-prefixed 32-byte key generated by
``pylar key:generate``. The prefix mirrors Laravel's convention so
operators can tell at a glance that the value is base64-encoded.

Ciphertext format
-----------------

``encrypt`` returns a URL-safe base64 string containing:

    nonce (12 bytes) || ciphertext || tag (16 bytes)

All packed into a single blob so the caller does not have to manage
nonce storage separately. Each call generates a fresh random nonce.
"""

from __future__ import annotations

import base64
import os

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from pylar.encryption.exceptions import DecryptionError, EncryptionError


class Encrypter:
    """Symmetric AES-256-GCM encryption keyed by ``APP_KEY``.

    Constructed by the container from the application's
    :class:`EncryptionConfig`. Controllers and services that need
    encryption declare ``encrypter: Encrypter`` in their ``__init__``
    and call :meth:`encrypt` / :meth:`decrypt`.

    Usage::

        enc = Encrypter(key=b"32-byte-key...")
        token = enc.encrypt(b"secret data")
        assert enc.decrypt(token) == b"secret data"
    """

    _NONCE_LENGTH = 12  # GCM standard

    def __init__(self, key: bytes) -> None:
        if len(key) != 32:
            raise EncryptionError(
                f"APP_KEY must be exactly 32 bytes, got {len(key)}. "
                "Run `pylar key:generate` to create one."
            )
        self._aesgcm = AESGCM(key)

    def encrypt(self, data: bytes) -> str:
        """Encrypt *data* and return a URL-safe base64 string.

        A fresh random nonce is generated for every call so the same
        plaintext never produces the same ciphertext.
        """
        nonce = os.urandom(self._NONCE_LENGTH)
        ciphertext = self._aesgcm.encrypt(nonce, data, None)
        # nonce + ciphertext (which includes the 16-byte GCM tag)
        return base64.urlsafe_b64encode(nonce + ciphertext).decode("ascii")

    def decrypt(self, token: str) -> bytes:
        """Decrypt a token returned by :meth:`encrypt`.

        Raises :class:`DecryptionError` if the token is malformed,
        tampered with, or encrypted with a different key.
        """
        try:
            raw = base64.urlsafe_b64decode(token)
        except Exception as exc:
            raise DecryptionError("Invalid base64 in encrypted token") from exc
        if len(raw) < self._NONCE_LENGTH + 16:
            raise DecryptionError("Token too short to contain nonce + tag")
        nonce = raw[: self._NONCE_LENGTH]
        ciphertext = raw[self._NONCE_LENGTH :]
        try:
            return self._aesgcm.decrypt(nonce, ciphertext, None)
        except Exception as exc:
            raise DecryptionError(
                "Decryption failed — wrong key or tampered data"
            ) from exc

    def encrypt_string(self, value: str) -> str:
        """Convenience: encrypt a UTF-8 string."""
        return self.encrypt(value.encode("utf-8"))

    def decrypt_string(self, token: str) -> str:
        """Convenience: decrypt back to a UTF-8 string."""
        return self.decrypt(token).decode("utf-8")

    @staticmethod
    def generate_key() -> str:
        """Generate a fresh random 32-byte key in ``base64:...`` format.

        This is what ``pylar key:generate`` calls. The ``base64:``
        prefix mirrors Laravel so operators recognise the format.
        """
        raw = os.urandom(32)
        return "base64:" + base64.b64encode(raw).decode("ascii")

    @staticmethod
    def key_from_string(app_key: str) -> bytes:
        """Parse a ``base64:...`` key string into raw bytes.

        Accepts both the prefixed format (``base64:ABC...``) and a
        bare base64 string for flexibility.
        """
        if app_key.startswith("base64:"):
            app_key = app_key[7:]
        try:
            raw = base64.b64decode(app_key)
        except Exception as exc:
            raise EncryptionError(
                f"APP_KEY is not valid base64: {exc}"
            ) from exc
        if len(raw) != 32:
            raise EncryptionError(
                f"APP_KEY must decode to 32 bytes, got {len(raw)}"
            )
        return raw
